// <auto-generated />
using System;
using BayesInferApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BayesInferApi.Migrations
{
    [DbContext(typeof(BayesInferContext))]
    partial class BayesInferContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BayesInferApi.Models.ArquivoRedeBayesiana", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArquivoJson");

                    b.Property<DateTime>("DataUpload");

                    b.Property<string>("Descricao");

                    b.Property<string>("NomeArquivo");

                    b.Property<string>("NomeRede");

                    b.HasKey("ID");

                    b.ToTable("ArquivosRedeBayesiana");
                });
#pragma warning restore 612, 618
        }
    }
}
